[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pgn_downloader/version.py"

[tool.mypy]
strict = true
files = "pgn_downloader/"
